---
title: "Document Analysis"
toc: true
format: 
  html:
    self-contained: true
---

# Document Analysis

## Findings for 'notify'

**Instance 1:**
*   **Chapter, Section, Page:** SECTION 1. ANIMAL DISEASE DIAGNOSIS, SURVEILLANCE AND NOTIFICATION, page iii
*   **Paragraph:**
    SECTION 1.                 ANIMAL DISEASE DIAGNOSIS, SURVEILLANCE AND **NOTIFICATION**
    Chapter 1.1.               Notification of diseases and provision of epidemiological information
    Chapter 1.2.               Criteria for the inclusion of diseases, infections and infestations in the WOAH list
    Chapter 1.3.               Diseases, infections and infestations listed by WOAH
    Chapter 1.4.               Animal health surveillance
    Chapter 1.5.               Surveillance for arthropod vectors of animal diseases
    Chapter 1.6.               Procedures for official recognition of animal health status, endorsement of an official control
                               programme, and publication of a self-declaration of animal health status, by WOAH
    Chapter 1.7.               Application for official recognition by WOAH of free status for African horse sickness
    Chapter 1.8.               Application for official recognition by WOAH of risk status for bovine spongiform
                               encephalopathy
    Chapter 1.9.               Application for official recognition by WOAH of free status for classical swine fever
    Chapter 1.10.              Application for official recognition by WOAH of free status for contagious bovine
                               pleuropneumonia
    Chapter 1.11.              Application for official recognition by WOAH of free status for foot and mouth disease
    Chapter 1.12.              Application for official recognition by WOAH of free status for peste des petits ruminants

**Instance 2:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, page iii
*   **Paragraph:**
    SECTION 1.                 ANIMAL DISEASE DIAGNOSIS, SURVEILLANCE AND NOTIFICATION
    Chapter 1.1.               **Notification** of diseases and provision of epidemiological information
    Chapter 1.2.               Criteria for the inclusion of diseases, infections and infestations in the WOAH list
    Chapter 1.3.               Diseases, infections and infestations listed by WOAH
    Chapter 1.4.               Animal health surveillance
    Chapter 1.5.               Surveillance for arthropod vectors of animal diseases
    Chapter 1.6.               Procedures for official recognition of animal health status, endorsement of an official control
                               programme, and publication of a self-declaration of animal health status, by WOAH
    Chapter 1.7.               Application for official recognition by WOAH of free status for African horse sickness
    Chapter 1.8.               Application for official recognition by WOAH of risk status for bovine spongiform
                               encephalopathy
    Chapter 1.9.               Application for official recognition by WOAH of free status for classical swine fever
    Chapter 1.10.              Application for official recognition by WOAH of free status for contagious bovine
                               pleuropneumonia
    Chapter 1.11.              Application for official recognition by WOAH of free status for foot and mouth disease
    Chapter 1.12.              Application for official recognition by WOAH of free status for peste des petits ruminants

**Instance 3:**
*   **Chapter, Section, Page:** Foreword, page vii
*   **Paragraph:**
    The Terrestrial Animal Health Code (the Terrestrial Code) provides standards for the improvement of animal health,
    animal welfare and veterinary public health worldwide. These standards should be used by Members to set up measures
    for the prevention, early detection, reporting and control of pathogenic agents in terrestrial animals (mammals, reptiles,
    birds and bees), including zoonotic agents. Implementation of the recommendations in the Terrestrial Code ensures the
    safety of international trade in animals and animal products, while avoiding unjustified sanitary barriers.

    The World Organisation for Animal Health (WOAH, founded as OIE) has developed and published international
    standards since 1968. The World Trade Organization (WTO) Agreement on the Application of Sanitary and
    Phytosanitary Measures (SPS Agreement) recognises the role of the Organisation (under its foundational name ’Office
    International des Epizooties’) as the international standard setting organisation for animal health and zoonoses.

    The development of new and revised standards for the Terrestrial Code is under the responsibility of the Terrestrial
    Animal Health Standards Commission (the Code Commission), which comprises six elected members. The Code
    Commission draws upon the expertise of internationally renowned experts to contribute to standards development to
    ensure that the standards are based on the latest scientific information. Comments from Members and partner
    International Organisations are sought through the twice-yearly circulation of new or revised texts. The Code
    Commission collaborates closely with other Specialist Commissions.

    The Terrestrial Code is published annually in English, French and Spanish and may be viewed and downloaded from
    the World Organisation for Animal Health website (www.woah.org).

    This edition includes new and amended texts in the following sections and chapters that were adopted by the World
    Assembly of Delegates of the World Organisation for Animal Health at the 91st General Session in May 2024:
    –    Glossary
    –    Disease, infections and infestations listed by WOAH (Chapter 1.3.)
    –    Application for official recognition by WOAH of free status for foot and mouth disease (Chapter 1.11.)
    –    General hygiene in semen collection and processing centres (Chapter 4.6.)
    –    Collection and processing of bovine, small ruminant and porcine semen (Chapter 4.7.)
    –    Responsible and prudent use of antimicrobial agents in veterinary medicine (Chapter 6.10.)
    –    Slaughter of animals (Chapter 7.5.)
    –    Infection with foot and mouth disease virus (Chapter 8.8.)
    –    Infection with Rift Valley fever virus (Chapter 8.16.)
    –    Infection with Trichinella spp. (Chapter 8.18.)
    –    Infection with Coxiella burnetii (Q fever) (a new Chapter 8.22.)
    –    Infection with Trypanosoma evansi (a new Chapter 8.23.)
    –    Rabbit haemorrhagic disease (Chapter 13.2.)
    –    Infection with African swine fever virus (Chapter 15.1.)
    –    Infection with Camelpox virus (a new Chapter 16.1)
    –    Terminology: Use of terms 'Competent Authority', 'Veterinary Authority' and 'Veterinary Services'.

    Details of the amendments made in this edition can be found in the 91st General Session report and Specialist
    Commissions reports, available on the World Organisation for Animal Health website (www.woah.org).

    I wish to thank the members of the Code Commission, Delegates, international experts and other Specialist
    Commissions for their expert advice. Thanks also to the World Organisation for Animal Health staff who contributed to
    the work that has resulted in the publication of this 32nd edition of the Terrestrial Code.

                                                       Dr Monique Eloit
                                                       Director General
                                              World Organisation for Animal Health

    2024 © OIE - Terrestrial Animal Health Code - 10/06/2024                                                              vii
    --- END OF PAGE ---

    Foreword

    Members of the Code Commission (2023-2024):
    President: Dr Etienne Bonbon
    Vice-President: Dr Gaston Maria Funes
    Vice-President: Prof. Salah Hammami
    Members: Dr Lucio Ignacio Carbajo Goñi, Dr Kiyokazu Murai and Dr Bernardo Todeschini.

    July 2024

    viii                                                 2024 © OIE - Terrestrial Animal Health Code - 10/06/2024
    --- END OF PAGE ---

                                                   USER'S GUIDE




                                                       A. Introduction
    1)   The WOAH Terrestrial Animal Health Code (hereafter referred to as the Terrestrial Code) establishes standards
         for the improvement of terrestrial animal health and welfare and veterinary public health worldwide. The purpose
         of this guide is to advise the Veterinary Authorities of WOAH Member Countries on how to use the Terrestrial Code.
    2)   Veterinary Authorities should use the standards in the Terrestrial Code to set up measures providing for early
         detection, internal reporting, **notification**, control or eradication of pathogenic agents, including zoonotic ones, in
         terrestrial animals (mammals, birds, reptiles and bees) and preventing their spread via international trade in
         animals and animal products, while avoiding unjustified sanitary barriers to trade.
    3)   WOAH standards are based on the most recent scientific and technical information. Correctly applied, they protect
         animal health and welfare and veterinary public health during production and trade in animals and animal products,
         and in the use of animals.
    4)   The absence of chapters, articles or recommendations on particular pathogenic agents or commodities does not
         preclude the application of appropriate sanitary measures by the Veterinary Authorities, provided they are based
         on risk analyses conducted in accordance with the Terrestrial Code.
    5)   The year that a chapter was first adopted and the year of its last revision are noted at the end of each chapter.
    6)   The complete text of the Terrestrial Code is available on WOAH Web site and individual chapters may be
         downloaded from: https://www.woah.org/.


                                                B. Terrestrial Code content
    1)   Key terms and expressions used in more than one chapter in the Terrestrial Code are defined in the Glossary, in
         the case where common dictionary definitions are not deemed to be adequate. The reader should be aware of the
         definitions given in the Glossary when reading and using the Terrestrial Code. Defined terms appear in italics. In
         the on-line version of the Terrestrial Code, a hyperlink leads to the relevant definition.
    2)   The term “(under study)” is found in some rare instances, with reference to an article or part of an article. This
         means that this part of the text has not been adopted by the World Assembly of Delegates and the particular
         provisions are thus not part of the Terrestrial Code.
    3)   The standards in the chapters of Section 1 are designed for the implementation of measures for the diagnosis,
         surveillance and **notification** of diseases, infections and infestations. The standards include procedures for
         **notification** to WOAH and procedures for the recognition of the animal health status of a country, zone or
         compartment.
    4)   The standards in Section 2 are designed to guide the importing country in conducting import risk analysis in the
         absence of WOAH recommendations on particular pathogenic agents or commodities. The importing country
         should also use these standards to justify import measures which are more stringent than existing WOAH
         standards.
    5)   The standards in the chapters of Section 3 are designed for the establishment, maintenance and evaluation of
         Veterinary Services, including veterinary legislation and communication. These standards are intended to assist
         the Veterinary Services and Veterinary Authority of Member Countries to meet their objectives of improving
         terrestrial animal health and welfare and veterinary public health, as well as to establish and maintain confidence
         in their international veterinary certificates.
    6)   The standards in the chapters of Section 4 are designed for the implementation of measures for the prevention and
         control of pathogenic agents. Measures in this section include animal identification, traceability, zoning,
         compartmentalisation, disposal of dead animals, disinfection, disinsection and general hygiene precautions. Some
         chapters address the specific sanitary measures to be applied for the collection and processing of semen and
         embryos of animals.
    7)   The standards in the chapters of Section 5 are designed for the implementation of general sanitary measures for
         trade. They address veterinary certification and the measures applicable by the exporting, transit and importing
         countries. A range of model veterinary certificates is provided to facilitate consistent documentation in international
         trade.

    2024 © OIE - Terrestrial Animal Health Code - 10/06/2024                                                                 ix
    --- END OF PAGE ---

    User's guide

    8)   The standards in the chapters of Section 6 are designed for the implementation of preventive measures in animal
         production systems. These measures are intended to assist Member Countries in meeting their veterinary public
         health objectives. They include ante- and post-mortem inspection, control of hazards in feed, biosecurity at the
         animal production level, and the control of antimicrobial resistance in animals.
    9)   The standards in the chapters of Section 7 are designed for the implementation of animal welfare measures. The
         standards cover production, transport, and slaughter or killing, as well as the animal welfare aspects of
         free-roaming dog population control and the use of animals in research and education.
    10) The standards in each of the chapters of Sections 8 to 16 are designed to prevent the pathogenic agents of WOAH
        listed diseases, infections or infestations from being introduced into an importing country. The standards take into
        account the nature of the traded commodity, the animal health status of the exporting country, zone or
        compartment, and the risk reduction measures applicable to each commodity.
         These standards assume that the agent is either not present in the importing country or is the subject of a control
         or eradication programme. Sections 8 to 16 each relate to the host species of the pathogenic agent: multiple
         species or species of Apinae, Aves, Bovinae, Equidae, Leporidae, Caprinae, Suidae and Camelidae. Some
         chapters include specific measures to prevent and control the infections of global concern. Although WOAH aims
         to include a chapter for each WOAH listed disease, not all WOAH listed diseases have been covered yet by a
         specific chapter. This is work in progress, depending on available scientific knowledge and the priorities set by the
         World Assembly of Delegates.

                                                       C. Specific issues
    1)   **Notification**
         Chapter 1.1. describes Member Countries' obligations under Organic Statutes of the Office International des
         Epizooties. Listed and emerging diseases, as prescribed in Chapter 1.1., are compulsorily notifiable. Member
         Countries are encouraged to also provide information to WOAH on other animal health events of epidemiological
         significance.
         Chapter 1.2. describes the criteria for the inclusion of an infection or infestation in the WOAH List and Chapter 1.3.
         gives the current list. Diseases are divided into nine categories based on the host species of the aetiological agents.
    2)   Diagnostic tests and vaccines
         It is recommended that specified diagnostic tests and vaccines in Terrestrial Code chapters be used with a
         reference to the relevant section in the WOAH Manual of Diagnostic Tests and Vaccines for Terrestrial Animals
         (hereafter referred to as the Terrestrial Manual). Experts responsible for facilities used for disease diagnosis and
         vaccine production should be fully conversant with the standards in the Terrestrial Manual.
    3)   Freedom from a disease, infection or infestation
         Article 1.4.6. provides general principles for declaring a country or zone free from a disease, infection or infestation.
         This article applies when there are no specific requirements in the listed disease-specific chapter.
    4)   Prevention and control
         Chapters 4.4. and 4.5. describe the measures that should be implemented to establish zones and compartments.
         Zoning and compartmentalisation should be considered as some of the tools used to control diseases and to
         facilitate safe trade.
         Chapters 4.6. to 4.12. describe the measures which should be implemented during collection and processing of
         semen and embryos of animals, including micromanipulation and cloning, in order to prevent animal health risks,
         especially when trading these commodities. Although the measures relate principally to WOAH listed diseases or
         infections, general standards apply to all infectious disease risks. Moreover, in Chapter 4.8. diseases that are not
         listed are marked as such but are included for the information of Member Countries.
         Chapter 4.15. addresses the specific issue of the control of bee diseases and some of its trade implications. This
         chapter should be read in conjunction with the specific bee disease chapters in Section 9.
         Chapter 6.5. is designed for the implementation of general biosecurity measures in intensive poultry production.
         Chapters 6.6., 6.13. and 6.14. provide recommendations for some specific on-farm prevention and control plans
         for the unlisted foodborne pathogenic agent Salmonella as part of the Veterinary Services mission to prevent,
         eliminate or control food safety hazards in animal production.
         Chapter 6.12. deals specifically with the zoonotic risk associated with the movements of non-human primates and
         gives standards for certification, transportation and import conditions for these animals.
    5)   Trade requirements
         Animal health measures related to international trade should be based on WOAH standards. A Member Country
         may authorise the importation of animals or animal products into its territory under conditions different from those
         recommended by the Terrestrial Code. To scientifically justify more stringent measures, the importing country

    x                                                           2024 © OIE - Terrestrial Animal Health Code - 10/06/2024
    --- END OF PAGE ---

                                                                                                              User's guide


         should conduct a risk analysis in accordance with WOAH standards, as described in Chapter 2.1. Members of the
         WTO should refer to the Agreement on the Application of Sanitary and Phytosanitary Measures (SPS Agreement).
         Chapters 5.1. to 5.3. describe the general obligations and ethical responsibilities of importing and exporting
         countries in international trade. Veterinary Authorities and all veterinarians directly involved in international trade
         should be familiar with these chapters. Chapter 5.3. also describes the WOAH informal procedure for dispute
         mediation.
         WOAH aims to include an article listing the commodities that are considered safe for trade without the need for risk
         mitigation measures specifically directed against a particular listed disease, infection or infestation, regardless of
         the status of the country or zone of origin for the agent in question, at the beginning of each listed disease-specific
         chapter in Sections 8 to 16. This is work in progress and some chapters do not yet contain articles listing safe
         commodities. When a list of safe commodities is present in a chapter, importing countries should not apply trade
         restrictions to such commodities with respect to the agent in question. Chapter 2.2. describes the criteria used to
         assess the safety of commodities.
    6)   International veterinary certificates
         An international veterinary certificate is an official document that the Veterinary Authority of an exporting country
         issues in accordance with Chapters 5.1. and 5.2. It lists animal health requirements and, where appropriate, public
         health requirements for the exported commodity. The quality of the exporting country's Veterinary Services is
         essential in providing assurances to trading partners regarding the safety of exported animals and products. This
         includes the Veterinary Authority's ethical approach to the provision of veterinary certificates and their history in
         meeting their **notification** obligations.
         International veterinary certificates underpin international trade and provide assurances to the importing country
         regarding the health status of the animals and products imported. The measures prescribed should take into
         account the health status of both exporting and importing countries, and zones or compartments within them, and
         be based upon the standards in the Terrestrial Code.
         The following steps should be taken when drafting international veterinary certificates:
         a)   identify the diseases, infections or infestations from which the importing country is justified in seeking
              protection because of its own health status. Importing countries should not impose measures in regards to
              diseases that occur in their own territory but are not subject to official control programmes;
         b)   for commodities capable of transmitting these diseases, infections or infestations through international trade,
              the importing country should apply the relevant articles in the listed disease-specific chapters. The application
              of the articles should be adapted to the disease status of the country, zone or compartment of origin. Such
              status should be established according to Article 1.4.6. except when articles of the relevant listed disease
              chapter specify otherwise;
         c)   when preparing international veterinary certificates, the importing country should endeavour to use terms and
              expressions in accordance with the definitions given in the Glossary. International veterinary certificates
              should be kept as simple as possible and should be clearly worded, to avoid misunderstanding of the
              importing country's requirements;
         d)   Chapters 5.10. to 5.13. provide, as further guidance to Member Countries, model certificates that should be
              used as a baseline.
    7)   Guidance notes for importers and exporters
         It is recommended that Veterinary Authorities prepare “guidance notes” to assist importers and exporters
         understand trade requirements. These notes should identify and explain the trade conditions, including the
         measures to be applied before and after export and during transport and unloading, and the relevant legal
         obligations and operational procedures. The guidance notes should advise on all details to be included in the health
         certification accompanying the consignment to its destination. Exporters should also be reminded of the
         International Air Transport Association rules governing air transport of animals and animal products.

    xii                                                         2024 © OIE - Terrestrial Animal Health Code - 10/06/2024
    --- END OF PAGE ---

                                                       GLOSSARY




    For the purposes of the Terrestrial Code:

    ANIMAL
         means a mammal, reptile, bird or bee.

    ANIMAL FOR BREEDING OR REARING
         means a domesticated or confined animal which is not intended for slaughter within a short time.

    ANIMAL FOR SLAUGHTER
         means an animal intended for slaughter within a short time, under the control of the relevant Competent Authority.

    ANIMAL HANDLER
         means a person with a knowledge of the behaviour and needs of animals who, with appropriate experience and a
         professional and positive response to an animal’s needs, can achieve effective management and good welfare.
         Competence should be gained through formal training or practical experience.

    ANIMAL HEALTH MANAGEMENT
         means a system designed to optimise the physical and behavioural health and welfare of animals. It includes the
         prevention, treatment and control of diseases and conditions affecting the individual animal and herd or flock,
         including the recording of illness, injuries, mortalities and medical treatments where appropriate.

    ANIMAL HEALTH STATUS
         means the status of a country, zone or compartment with respect to an animal disease in accordance with the
         criteria listed in the relevant disease-specific chapter or Chapter 1.4. of the Terrestrial Code.

    ANIMAL IDENTIFICATION
         means the combination of the identification and registration of an animal individually, with a unique identifier, or
         collectively by its epidemiological unit or group, with a unique group identifier.

    ANIMAL IDENTIFICATION SYSTEM
         means the inclusion and linking of components such as identification of establishments or owners, the persons
         responsible for the animals, movements and other records with animal identification.

    ANIMAL PRODUCT
         means any part of an animal, or a raw or manufactured product containing any material derived from animals,
         excluding germinal products, biological products and pathological material.

    ANIMAL TRACEABILITY
         means the ability to follow an animal or group of animals during all stages of its life.

    ANIMAL WELFARE
         means the physical and mental state of an animal in relation to the conditions in which it lives and dies.

    ANTIMICROBIAL AGENT
         means a naturally occurring, semi-synthetic or synthetic substance that exhibits antimicrobial activity (kill or inhibit
         the growth of micro-organisms) at concentrations attainable in vivo. Anthelmintics and substances classed as
         disinfectants or antiseptics are excluded from this definition.

    APIARY
         means a beehive or group of beehives whose management allows them to be considered as a single
         epidemiological unit.

    APPROVED
         means officially approved, accredited or registered by the Veterinary Authority.

    2024 © OIE - Terrestrial Animal Health Code - 10/06/2024                                                                xiii
    --- END OF PAGE ---

    Glossary


    BEEHIVE

           means a structure for the keeping of honey bee colonies that is being used for that purpose, including frameless
           hives, fixed frame hives and all designs of moveable frame hives (including nucleus hives), but not including
           packages or cages used to confine bees for the purposes of transport or isolation.

    BIOLOGICAL PRODUCT

           means a product of animal or microorganism origin, used in the diagnosis of diseases, for treatment, control and
           prevention of diseases, or in the collection and processing of germinal products.

    BIOSECURITY

           means a set of management and physical measures designed to reduce the risk of introduction, establishment and
           spread of animal diseases, infections or infestations to, from and within an animal population.

    BIOSECURITY PLAN

           means a plan that identifies potential pathways for the introduction and spread of disease in a zone or
           compartment, and describes the measures which are being or will be applied to mitigate the disease risks, if
           applicable, in accordance with the recommendations in the Terrestrial Code.

    BORDER POST

           means any airport, or any port, railway station or road check-point open to international trade of commodities,
           where import veterinary inspections can be performed.

    CAPTIVE WILD [ANIMAL]

           means an animal that has a phenotype not significantly affected by human selection but that is captive or otherwise
           lives under or requires human supervision or control.

    CASE

           means an individual animal infected by a pathogenic agent, with or without clinical signs.

    CASINGS

           means intestines and bladders that, after cleaning, have been processed by tissue scraping, defatting and washing,
           and have been treated with salt.

    COLLECTION CENTRE

           means a facility approved by the Veterinary Authority for the collection of oocytes or embryos and used exclusively
           for donor animals which meet the conditions of the Terrestrial Code.

    COMMODITY

           means a live animal, an animal product, germinal products, a biological product or pathological material.

    COMPARTMENT

           means an animal subpopulation contained in one or more establishments, separated from other susceptible
           populations by a common biosecurity management system, and with a specific animal health status with respect
           to one or more infections or infestations for which the necessary surveillance, biosecurity and control measures
           have been applied for the purposes of international trade or disease prevention and control in a country or zone.

    COMPETENT AUTHORITY

           means a Governmental Authority of a Member Country having the responsibility in the whole or part of the territory
           for the implementation of certain standards of the Terrestrial Code.

    CONTAINER

           means a non-self-propelled receptacle or other rigid structure for holding animals during a journey by one or several
           means of transport.

    CONTAINMENT ZONE

           means an infected zone defined within a previously free country or zone, which includes all suspected or confirmed
           cases that are epidemiologically linked and where movement control, biosecurity and sanitary measures are
           applied to prevent the spread of, and to eradicate, the infection or infestation.

    DAY-OLD BIRDS

           means birds aged not more than 72 hours after hatching.

    xiv                                                         2024 © OIE - Terrestrial Animal Health Code - 10/06/2024
    --- END OF PAGE ---

    Glossary


    DISINFECTION

           means the application, after thorough cleansing, of procedures intended to destroy the infectious or parasitic
           agents of animal diseases, including zoonoses; this applies to premises, vehicles and different objects which may
           have been directly or indirectly contaminated.

    DISINFESTATION

           means the application of procedures intended to eliminate infestation.

    DISTRESS

           means the state of an animal, that has been unable to adapt to stressors, and that manifests as abnormal
           physiological or behavioural responses. It can be acute or chronic and may result in pathological conditions.

    EARLY WARNING SYSTEM

           means a system for the timely detection, reporting and communication of occurrence, incursion or emergence of
           diseases, infections or infestations in a country, zone or compartment.

    EMERGING DISEASE

           means a new occurrence in an animal of a disease, infection or infestation, causing a significant impact on animal
           or public health resulting from:
           a)   a change of a known pathogenic agent or its spread to a new geographic area or species; or
           b)   a previously unrecognised pathogenic agent or disease diagnosed for the first time.

    EPIDEMIOLOGICAL UNIT

           means a group of animals with the same likelihood of exposure to a pathogenic agent. In certain circumstances,
           the epidemiological unit may be a single animal.

    ERADICATION

           means the elimination of a pathogenic agent from a country or zone.

    ESTABLISHMENT

           means the premises in which animals are kept.

    EUTHANASIA

           means the killing of an animal using a method that causes a rapid and irreversible loss of consciousness with
           minimum pain and distress.

    EXPORTING COUNTRY

           means a country from which commodities are sent to another country.

    FEED

           means any material (single or multiple), whether processed, semi-processed or raw, which is intended to be fed
           directly to terrestrial animals (except bees).

    FEED INGREDIENT

           means a component part or constituent of any combination or mixture making up a feed, whether or not it has a
           nutritional value in the animal's diet, including feed additives. Ingredients are of plant (including aquatic plants) or
           terrestrial or aquatic animal origin, or other organic or inorganic substances.

    FERAL [ANIMAL]

           means an animal of a domesticated species that lives without requiring human supervision or control.

    FLOCK

           means a number of animals of one kind kept together under human control or a congregation of gregarious wild
           animals. A flock is usually regarded as an epidemiological unit.

    FREE COMPARTMENT

           means a compartment in which the absence of the animal pathogenic agent causing the disease under
           consideration has been demonstrated by all requirements specified in the Terrestrial Code for free status being
           met.

    xv
    --- END OF PAGE ---

    Glossary


    FREE-ROAMING DOG
           means any owned dog or unowned dog that is without direct human supervision or control, including feral dogs.

    FREE ZONE
           means a zone in which the absence of a specific infection or infestation in an animal population has been
           demonstrated in accordance with the relevant requirements of the Terrestrial Code.

    FRESH MEAT
           means meat that has not been subjected to any treatment irreversibly modifying its organoleptic and
           physicochemical characteristics. This includes frozen meat, chilled meat, minced meat and mechanically
           recovered meat.

    GERMINAL PRODUCTS
           means animal semen, oocytes, embryos or hatching eggs.

    GOOD MANUFACTURING PRACTICE
           means a production and testing practice recognised by the Competent Authority to ensure the quality of a product.

    GREAVES
           means the protein-containing residue obtained after the partial separation of fat and water during the process of
           rendering.

    HATCHING EGGS
           means fertilised bird eggs, suitable for incubation and hatching.

    HAZARD
           means a biological, chemical or physical agent in, or a condition of, an animal or animal product with the potential
           to cause an adverse health effect.

    HEADQUARTERS
           means the Permanent Secretariat of the World Organisation for Animal Health located at:
           12, rue de Prony, 75017 Paris, FRANCE
           Telephone: 33-(0)1 44 15 18 88
           Fax: 33-(0)1 42 67 09 87
           Electronic mail: woah@woah.org
           WWW: http://www.woah.org

    HERD
           means a number of animals of one kind kept together under human control or a congregation of gregarious wild
           animals. A herd is usually regarded as an epidemiological unit.

    IMPORTING COUNTRY
           means a country that is the final destination to which commodities are sent.

    INCIDENCE
           means the number of new cases or outbreaks of a disease that occur in a population at risk in a particular
           geographical area within a defined time interval.

    INCUBATION PERIOD
           means the longest period that elapses between the introduction of the pathogenic agent into the animal and the
           occurrence of the first clinical signs of the disease.

    INFECTED ZONE
           means a zone either in which an infection or infestation has been confirmed, or one that is defined as such in the
           relevant chapters of the Terrestrial Code.

    INFECTION
           means the entry and development or multiplication of a pathogenic agent in the body of humans or animals.

    INFECTIVE PERIOD
           means the longest period during which an affected animal can be a source of infection.

    xvi                                                         2024 © OIE - Terrestrial Animal Health Code - 10/06/2024
    --- END OF PAGE ---

                                                                                                        Glossary


    INFESTATION

           means the external invasion or colonisation of animals or their immediate surroundings by arthropods, which may
           cause clinical signs or are potential vectors of pathogenic agents.

    INTERNATIONAL TRADE

           means importation, exportation and transit of commodities.

    INTERNATIONAL VETERINARY CERTIFICATE

           means a certificate, issued in accordance with Chapter 5.2., describing the animal health and public health
           requirements that are fulfilled by the exported commodities.

    JOURNEY

           An animal transport journey commences when the first animal is loaded onto a vehicle/vessel or into a container
           and ends when the last animal is unloaded, and includes any stationary resting/holding periods. The same animals
           do not commence a new journey until after a suitable period for rest and recuperation, with adequate feed and
           water.

    KILLING

           means any procedure that causes the death of an animal.

    LABORATORY

           means a properly equipped institution staffed by technically competent personnel under the control of a specialist
           in veterinary diagnostic methods, who is responsible for the validity of the results. The Veterinary Authority
           approves and monitors such laboratories with regard to the diagnostic tests required for international trade.

    LAIRAGE

           means pens, yards and other holding areas used for accommodating animals in order to give them necessary
           attention (such as water, feed, rest) before they are moved on or used for specific purposes including slaughter.

    LISTED DISEASE

           means a disease, infection or infestation listed in Chapter 1.3. after adoption by the World Assembly of Delegates.

    LOADING/UNLOADING

           Loading means the procedure of moving animals onto a vehicle/vessel or into a container for transport purposes,
           while unloading means the procedure of moving animals off a vehicle/vessel or out of a container.

    MARKET

           means a place where animals are assembled for the purposes of trade or sale.

    MEAT

           means all edible parts of an animal.

    MEAT PRODUCTS

           means meat that has been subjected to a treatment irreversibly modifying its organoleptic and physicochemical
           characteristics.

    MILK

           means the normal mammary secretion of milking animals obtained from one or more milkings without either
           addition to it or extraction from it.

    MILK PRODUCT

           means the product obtained by any processing of milk.

    MONITORING

           means the intermittent performance and analysis of routine measurements and observations, aimed at detecting
           changes in the environment or health status of a population.

    NOTIFIABLE DISEASE

           means a disease listed by the Veterinary Authority, and that, as soon as detected or suspected, should be brought
           to the attention of this Authority, in accordance with national regulations.

    xvii
    --- END OF PAGE ---

    Glossary


    **NOTIFICATION**

            means the procedure by which:
            a)   the Veterinary Authority informs the Headquarters,
            b)   the Headquarters inform the Veterinary Authority,
            of the occurrence of disease, infection or infestation in accordance with Chapter 1.1.

**Instance 4:**
*   **Chapter, Section, Page:** Glossary, page xvii
*   **Paragraph:**
    NOTIFIABLE DISEASE

           means a disease listed by the Veterinary Authority, and that, as soon as detected or suspected, should be brought
           to the attention of this Authority, in accordance with national regulations.

    **NOTIFICATION**

            means the procedure by which:
            a)   the Veterinary Authority informs the Headquarters,
            b)   the Headquarters inform the Veterinary Authority,
            of the occurrence of disease, infection or infestation in accordance with Chapter 1.1.

**Instance 5:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.1., page 1
*   **Paragraph:**
    CHAPTER 1.1.

    **NOTIFICATION** OF DISEASES AND PROVISION OF
          EPIDEMIOLOGICAL INFORMATION

                                                         Article 1.1.1.

    For the purposes of the Terrestrial Code and in terms of Articles 5, 9 and 10 of the Organic Statutes of the Office
    International des Epizooties, Member Countries shall recognise the right of the Headquarters to communicate directly
    with the Veterinary Authority of its territory or territories.

    All **notifications** and all information sent by WOAH to the Veterinary Authority shall be regarded as having been sent to
    the country concerned and all **notifications** and all information sent to WOAH by the Veterinary Authority shall be
    regarded as having been sent by the country concerned.

**Instance 6:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.1., page 1
*   **Paragraph:**
    CHAPTER 1.1.

    NOTIFICATION OF DISEASES AND PROVISION OF
          EPIDEMIOLOGICAL INFORMATION

                                                         Article 1.1.1.

    For the purposes of the Terrestrial Code and in terms of Articles 5, 9 and 10 of the Organic Statutes of the Office
    International des Epizooties, Member Countries shall recognise the right of the Headquarters to communicate directly
    with the Veterinary Authority of its territory or territories.

    All **notifications** and all information sent by WOAH to the Veterinary Authority shall be regarded as having been sent to
    the country concerned and all **notifications** and all information sent to WOAH by the Veterinary Authority shall be
    regarded as having been sent by the country concerned.

**Instance 7:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the **notification** requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks reported from the time of the
         initial notification through to the final report. Reports of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, reports shall conform as closely as possible to the
         WOAH disease reporting format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be reported, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their reports, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 8:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a **notification**. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks reported from the time of the
         initial **notification** through to the final report. Reports of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, reports shall conform as closely as possible to the
         WOAH disease reporting format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be reported, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their reports, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 9:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks reported from the time of the
         initial **notification** through to the final report. Reports of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, reports shall conform as closely as possible to the
         WOAH disease reporting format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be reported, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their reports, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to **notifying** new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 10:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, **notification**, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly reports subsequent to a **notification** under point 1 above, to provide further information on the evolution of
         the event which justified the **notification**. These reports should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly reporting under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final report should be submitted;
    3)   six-monthly reports on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual reports concerning any other information of significance to other Member Countries.

**Instance 11:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly reports subsequent to a **notification** under point 1 above, to provide further information on the evolution of
         the event which justified the **notification**. These reports should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly reporting under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final report should be submitted;
    3)   six-monthly reports on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual reports concerning any other information of significance to other Member Countries.

**Instance 12:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly reports subsequent to a notification under point 1 above, to provide further information on the evolution of
         the event which justified the notification. These reports should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly reporting under point 3 will satisfy the obligation of
         the Member Country. For each event **notified**, a final report should be submitted;
    3)   six-monthly reports on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual reports concerning any other information of significance to other Member Countries.

**Instance 13:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.4., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.4.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   a **notification** through WAHIS or by fax or email, when an emerging disease has been detected in a country, a zone
         or a compartment;

    2)   periodic reports subsequent to a **notification** of an emerging disease:
         a)   for the time necessary to have reasonable certainty that:
              i)    the infection or infestation has been eradicated; or
              ii)   the situation has become stable;
         OR
         b)   until sufficient scientific information is available to determine whether it meets the criteria for inclusion in the
              WOAH list as described in Chapter 1.2.;
    3)   a final report once point 2 a) or 2 b) above has been complied with.

**Instance 14:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.4., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.4.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   a **notification** through WAHIS or by fax or email, when an emerging disease has been detected in a country, a zone
         or a compartment;

    2)   periodic reports subsequent to a **notification** of an emerging disease:
         a)   for the time necessary to have reasonable certainty that:
              i)    the infection or infestation has been eradicated; or
              ii)   the situation has become stable;
         OR
         b)   until sufficient scientific information is available to determine whether it meets the criteria for inclusion in the
              WOAH list as described in Chapter 1.2.;
    3)   a final report once point 2 a) or 2 b) above has been complied with.

**Instance 15:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.5., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.5.

    1)   Although Member Countries are only required to **notify** listed diseases and emerging diseases, they are
         encouraged to provide WOAH with other important animal health information.
    2)   The Headquarters shall communicate by email or through the interface of WAHIS to Veterinary Authorities all
         notifications received as provided in Articles 1.1.2. to 1.1.4. and other relevant information.

**Instance 16:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.5., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.5.

    1)   Although Member Countries are only required to notify listed diseases and emerging diseases, they are
         encouraged to provide WOAH with other important animal health information.
    2)   The Headquarters shall communicate by email or through the interface of WAHIS to Veterinary Authorities all
         **notifications** received as provided in Articles 1.1.2. to 1.1.4. and other relevant information.

**Instance 17:**
*   **Chapter, Section, Page:** Chapter 1.2. Criteria for the inclusion of diseases, infections and infestations in the WOAH list, Article 1.2.1., page 3
*   **Paragraph:**
    CHAPTER 1.2.

               CRITERIA FOR THE INCLUSION OF
           DISEASES, INFECTIONS AND INFESTATIONS
                      IN THE WOAH LIST

                                                       Article 1.2.1.

    Introduction

    This chapter describes the criteria for the inclusion of diseases, infections and infestations in Chapter 1.3.

    The objective is to support Member Countries by providing information needed to take appropriate action to prevent the
    transboundary spread of important animal diseases, including zoonoses. This is achieved through transparent, timely
    and consistent notification.

    The requirements for **notification** are detailed in Chapter 1.1.

    Principles and methods of validation of diagnostic tests are described in Chapter 1.1.6. of the Terrestrial Manual.

**Instance 18:**
*   **Chapter, Section, Page:** Chapter 1.6. Procedures for official recognition of animal health status, endorsement of an official control programme, and publication of a self-declaration of animal health status, by WOAH, Article 1.6.2., page 20
*   **Paragraph:**
    CHAPTER 1.6.- Procedures for official recognition of animal health status, endorsement of an official control
    programme, and publication of a self-declaration of animal health status, by WOAH

                                                       Article 1.6.2.

    Maintenance of official recognition of animal health status and endorsement of an official control programme by
    WOAH

    Retention on the lists of countries and zones having an official animal health status or of countries having an endorsed
    official control programme requires that the information in relevant chapters be re-submitted annually and that changes
    in the epidemiological situation or other significant events be **notified** to WOAH in accordance with the requirements in
    Chapter 1.1.

    Non-compliance with the requirements for the maintenance of animal health status results in the suspension of that
    status. Within 24 months of suspension, except otherwise stated in the disease-specific chapter, a Member Country
    may apply for the recovery of a previously recognised status, following the provisions of the relevant disease-specific
    chapter. When the status has not been recovered within the specified period of its suspension, it is withdrawn and the
    Member Country should reapply following the procedure for the application for official recognition of animal health
    status.

    WOAH may withdraw the endorsement of an official control programme if there is evidence of:
    –    non-compliance with the timelines or performance indicators of the programme; or
    –    significant problems with the quality of the Veterinary Services as described in Section 3 of the Terrestrial Code; or
    –    an increase in the incidence or distribution of the disease that cannot be addressed by the programme.

**Instance 19:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.1., page 24
*   **Paragraph:**
    5.   AHS surveillance
         Provide documentary evidence that surveillance for AHS in the country complies with Articles 12.1.11. to
         12.1.13. of the Terrestrial Code, and Chapter 3.5.1. of the Terrestrial Manual. The following information should be
         included:
         a)   What are the criteria for raising a suspicion of AHS? What is the procedure to **notify** (by whom and to whom)
              and what incentives are there for reporting and what penalties are involved for failure to report?
         b)   Describe how clinical surveillance is conducted, including which equine sectors are included in clinical
              surveillance, such as establishments, markets, fairs, slaughterhouses/abattoirs, check points, etc.
              Provide a summary table indicating, for the past 24 months, the number of suspected cases, the number of
              samples tested for AHS, species, type of sample, testing methods and results (including differential
              diagnosis). Provide an indication of the timelines of the response including completion of testing to confirm or
              exclude AHS. Provide details of follow-up actions taken on all suspicious and positive results.
         c)   Other surveillance. Is surveillance undertaken as described in Article 12.1.13., specifically:
              i)     Serological surveillance.
              ii)    Virological surveillance including genome or antigen detection.
              iii)   Sentinel animals.
              iv)    Vector surveillance.
              If so, provide detailed information on the target population, design prevalence, confidence level, sample size,
              stratification, sampling methods and diagnostic tests used in accordance with Articles 12.1.11. and
              12.1.13. of the Terrestrial Code. How frequently are they conducted? Which equine species are included? Are
              wildlife species included? If not, explain the rationale.
              Provide a summary table and maps indicating detailed results for at least the past 24 months. Provide details
              of follow-up actions taken on all suspicious and positive results and how these findings are acted upon.
              Provide criteria for selection of populations for targeted surveillance and numbers of equids examined and
              samples tested in diagnostic laboratories. Provide details of the methods selected and applied for monitoring
              the performance of the surveillance programme including indicators.
         d)   Provide information on risks in the different equine sectors, and provide evidence that targeted studies are
              implemented to address gaps (e.g. targeted serological surveys, active surveillance, participatory
              epidemiology studies, risk assessments, etc.). Provide evidence of how the knowledge acquired through
              these activities assisted in more effective implementation of control measures.
         e)   Provide details of the oversight of surveillance programmes by the Veterinary Services including training
              programmes for personnel involved in clinical, serological, virological and other surveillance, and the
              approaches used to increase community involvement in AHS surveillance programmes.

**Instance 20:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.2., page 28
*   **Paragraph:**
    5.   AHS surveillance

         Provide documentary evidence that surveillance for AHS in the zone complies with Articles 12.1.11. to 12.1.13. of
         the Terrestrial Code, and Chapter 3.5.1. of the Terrestrial Manual. The following information should be included:
         a)   What are the criteria for raising a suspicion of AHS? What is the procedure to **notify** (by whom and to whom)
              and what incentives are there for reporting and what penalties are involved for failure to report?
         b)   Describe how clinical surveillance is conducted, including which equine sectors are included in clinical
              surveillance, such as establishments, markets, fairs, slaughterhouses/abattoirs, check points, etc.

              Provide a summary table indicating, for the past 24 months, the number of suspected cases, the number of
              samples tested for AHS, species, type of sample, testing methods and results (including differential
              diagnosis). Provide an indication of the timelines of the response including completion of testing to confirm or
              exclude AHS. Provide details of follow-up actions taken on all suspicious and positive results.
         c)   Other surveillance. Is surveillance undertaken as described in Article 12.1.13., specifically:
              i)     Serological surveillance.
              ii)    Virological surveillance including genome or antigen detection.

## Findings for 'notifiable disease'

**Instance 1:**
*   **Chapter, Section, Page:** User's Guide, C. Specific issues, 1) Notification, page ix
*   **Paragraph:**
    1)   Notification
         Chapter 1.1. describes Member Countries' obligations under Organic Statutes of the Office International des
         Epizooties. Listed and emerging diseases, as prescribed in Chapter 1.1., are compulsorily **notifiable**. Member
         Countries are encouraged to also provide information to WOAH on other animal health events of epidemiological
         significance.
         Chapter 1.2. describes the criteria for the inclusion of an infection or infestation in the WOAH List and Chapter 1.3.
         gives the current list. Diseases are divided into nine categories based on the host species of the aetiological agents.

**Instance 2:**
*   **Chapter, Section, Page:** Glossary, page xvii
*   **Paragraph:**
    MILK PRODUCT

           means the product obtained by any processing of milk.

    MONITORING

           means the intermittent performance and analysis of routine measurements and observations, aimed at detecting
           changes in the environment or health status of a population.

    **NOTIFIABLE DISEASE**

           means a disease listed by the Veterinary Authority, and that, as soon as detected or suspected, should be brought
           to the attention of this Authority, in accordance with national regulations.

**Instance 3:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.5., page 13
*   **Paragraph:**
    An early warning system is essential for the timely detection, reporting and communication of occurrence, incursion or
    emergence of diseases, infections or infestations and is an integral component of emergency preparedness. It should
    be under the control of the Veterinary Authority and should include the following:
    1)   appropriate access to, and authority over, the target animal populations by the Veterinary Services;
    2)   access to laboratories capable of diagnosing and differentiating relevant infections or infestations;
    3)   training and awareness programmes for veterinarians, veterinary paraprofessionals, animal owners or keepers and
         others involved in handling animals at the farm or other places where they are kept during their transport or at the
         slaughterhouse/abattoir, for detecting and reporting unusual animal health incidents;
    4)   a legal obligation by veterinarians and other relevant stakeholders to report suspected cases or cases of **notifiable
         diseases** or emerging diseases to the Veterinary Authority, including the description of the findings;
    5)   epidemiological investigations of suspected cases and cases conducted by the Veterinary Services in order to
         confirm cases and to acquire accurate knowledge of the situation for further action.
         All suspected case investigations should provide a result, either positive or negative. Criteria should be established
         in advance for a case definition. Confirmation can be made on clinical and post-mortem grounds, epidemiological
         information, laboratory test results or a combination of these, in accordance with relevant articles of the Terrestrial
         Code or Terrestrial Manual;
    6)   effective systems of communication between the Veterinary Authority and relevant stakeholders;
    7)   a national chain of command.

**Instance 4:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.6., page 14
*   **Paragraph:**
    2.   Requirements to declare a country or a zone free from an infection or infestation
         a)   Prerequisites, unless otherwise specified in the relevant chapters of the Terrestrial Code:
              i)     the infection or infestation has been a **notifiable disease**;
              ii)    an early warning system has been in place for all relevant species;
              iii)   measures to prevent the introduction of the infection or infestation have been in place: in particular, the
                     importations or movements of commodities into the country or zone have been carried out in accordance
                     with the relevant chapters of the Terrestrial Code;
              iv)    the infection or infestation is not known to be established in wildlife within the country or zone.
         b)   Historical freedom
              Unless otherwise specified in the relevant chapter of the Terrestrial Code, a country or zone may be
              considered free without formally applying a pathogen-specific surveillance programme when:
              i)     for at least the past 10 years:
                     –    no vaccination against the disease has been carried out;
                     –    the prerequisites listed in point a) are complied with;
              ii)    the pathogenic agent is likely to produce identifiable clinical or pathological signs in susceptible animals;
              iii)   for at least 25 years there has been no occurrence of infection or infestation.
         c)   Where historical freedom cannot be demonstrated:
              i)     A pathogen-specific surveillance programme has been applied as described in this chapter and in the
                     relevant chapter of the Terrestrial Code, and has not detected any occurrence of the infection or
                     infestation.
              ii)    The prerequisites listed in point a) have been complied with for at least as long as the pathogen-specific
                     surveillance has been in place.

**Instance 5:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.6., page 15
*   **Paragraph:**
    4.   Recommendations for the maintenance of freedom from a disease, infection or infestation
         Unless otherwise specified in the relevant chapter of the Terrestrial Code, a country or zone that has achieved
         freedom in accordance with the provisions of the Terrestrial Code may maintain its free status provided that:
         a)   the infection or infestation is a **notifiable disease**;
         b)   an early warning system is in place for all relevant species;
         c)   measures to prevent the introduction of the infection or infestation are in place;
         d)   surveillance adapted to the likelihood of occurrence of infection or infestation is carried out. Specific
              surveillance may not need to be carried out if supported by a risk assessment addressing all identified
              pathways for introduction of the pathogenic agent and provided the pathogenic agent is likely to produce
              identifiable clinical or pathological signs in susceptible animals;
         e)   the infection or infestation is not known to be established in wildlife.

**Instance 6:**
*   **Chapter, Section, Page:** Chapter 1.8. Application for official recognition by WOAH of risk status for bovine spongiform encephalopathy, Article 1.8.5., page 38
*   **Paragraph:**
    2.   BSE reporting system (point 3 b) of Article 11.4.20.)
         a)    Describe the BSE reporting system, including the date of implementation of any supporting legislation and
               associated policies making BSE a **notifiable disease**. Indicate if a definition for a suspicion of BSE' exists. If
               appropriate, outline relevant legislation in the table under Article 1.8.2.
         b)    Describe the supportive measures in place for targeting animals that show signs of the clinical spectrum of
               BSE and for reporting of animals described in points 2 a) to 2 d) of Article 11.4.20., such as incentives,
               compensations or penalties.

## Findings for 'report'

**Instance 1:**
*   **Chapter, Section, Page:** Foreword, page vii
*   **Paragraph:**
    The Terrestrial Animal Health Code (the Terrestrial Code) provides standards for the improvement of animal health,
    animal welfare and veterinary public health worldwide. These standards should be used by Members to set up measures
    for the prevention, early detection, **reporting** and control of pathogenic agents in terrestrial animals (mammals, reptiles,
    birds and bees), including zoonotic agents. Implementation of the recommendations in the Terrestrial Code ensures the
    safety of international trade in animals and animal products, while avoiding unjustified sanitary barriers.

    The World Organisation for Animal Health (WOAH, founded as OIE) has developed and published international
    standards since 1968. The World Trade Organization (WTO) Agreement on the Application of Sanitary and
    Phytosanitary Measures (SPS Agreement) recognises the role of the Organisation (under its foundational name ’Office
    International des Epizooties’) as the international standard setting organisation for animal health and zoonoses.

    The development of new and revised standards for the Terrestrial Code is under the responsibility of the Terrestrial
    Animal Health Standards Commission (the Code Commission), which comprises six elected members. The Code
    Commission draws upon the expertise of internationally renowned experts to contribute to standards development to
    ensure that the standards are based on the latest scientific information. Comments from Members and partner
    International Organisations are sought through the twice-yearly circulation of new or revised texts. The Code
    Commission collaborates closely with other Specialist Commissions.

    The Terrestrial Code is published annually in English, French and Spanish and may be viewed and downloaded from
    the World Organisation for Animal Health website (www.woah.org).

    This edition includes new and amended texts in the following sections and chapters that were adopted by the World
    Assembly of Delegates of the World Organisation for Animal Health at the 91st General Session in May 2024:
    –    Glossary
    –    Disease, infections and infestations listed by WOAH (Chapter 1.3.)
    –    Application for official recognition by WOAH of free status for foot and mouth disease (Chapter 1.11.)
    –    General hygiene in semen collection and processing centres (Chapter 4.6.)
    –    Collection and processing of bovine, small ruminant and porcine semen (Chapter 4.7.)
    –    Responsible and prudent use of antimicrobial agents in veterinary medicine (Chapter 6.10.)
    –    Slaughter of animals (Chapter 7.5.)
    –    Infection with foot and mouth disease virus (Chapter 8.8.)
    –    Infection with Rift Valley fever virus (Chapter 8.16.)
    –    Infection with Trichinella spp. (Chapter 8.18.)
    –    Infection with Coxiella burnetii (Q fever) (a new Chapter 8.22.)
    –    Infection with Trypanosoma evansi (a new Chapter 8.23.)
    –    Rabbit haemorrhagic disease (Chapter 13.2.)
    –    Infection with African swine fever virus (Chapter 15.1.)
    –    Infection with Camelpox virus (a new Chapter 16.1)
    –    Terminology: Use of terms 'Competent Authority', 'Veterinary Authority' and 'Veterinary Services'.

    Details of the amendments made in this edition can be found in the 91st General Session **report** and Specialist
    Commissions **reports**, available on the World Organisation for Animal Health website (www.woah.org).

    I wish to thank the members of the Code Commission, Delegates, international experts and other Specialist
    Commissions for their expert advice. Thanks also to the World Organisation for Animal Health staff who contributed to
    the work that has resulted in the publication of this 32nd edition of the Terrestrial Code.

                                                       Dr Monique Eloit
                                                       Director General
                                              World Organisation for Animal Health

**Instance 2:**
*   **Chapter, Section, Page:** Foreword, page vii
*   **Paragraph:**
    The Terrestrial Animal Health Code (the Terrestrial Code) provides standards for the improvement of animal health,
    animal welfare and veterinary public health worldwide. These standards should be used by Members to set up measures
    for the prevention, early detection, **reporting** and control of pathogenic agents in terrestrial animals (mammals, reptiles,
    birds and bees), including zoonotic agents. Implementation of the recommendations in the Terrestrial Code ensures the
    safety of international trade in animals and animal products, while avoiding unjustified sanitary barriers.

    The World Organisation for Animal Health (WOAH, founded as OIE) has developed and published international
    standards since 1968. The World Trade Organization (WTO) Agreement on the Application of Sanitary and
    Phytosanitary Measures (SPS Agreement) recognises the role of the Organisation (under its foundational name ’Office
    International des Epizooties’) as the international standard setting organisation for animal health and zoonoses.

    The development of new and revised standards for the Terrestrial Code is under the responsibility of the Terrestrial
    Animal Health Standards Commission (the Code Commission), which comprises six elected members. The Code
    Commission draws upon the expertise of internationally renowned experts to contribute to standards development to
    ensure that the standards are based on the latest scientific information. Comments from Members and partner
    International Organisations are sought through the twice-yearly circulation of new or revised texts. The Code
    Commission collaborates closely with other Specialist Commissions.

    The Terrestrial Code is published annually in English, French and Spanish and may be viewed and downloaded from
    the World Organisation for Animal Health website (www.woah.org).

    This edition includes new and amended texts in the following sections and chapters that were adopted by the World
    Assembly of Delegates of the World Organisation for Animal Health at the 91st General Session in May 2024:
    –    Glossary
    –    Disease, infections and infestations listed by WOAH (Chapter 1.3.)
    –    Application for official recognition by WOAH of free status for foot and mouth disease (Chapter 1.11.)
    –    General hygiene in semen collection and processing centres (Chapter 4.6.)
    –    Collection and processing of bovine, small ruminant and porcine semen (Chapter 4.7.)
    –    Responsible and prudent use of antimicrobial agents in veterinary medicine (Chapter 6.10.)
    –    Slaughter of animals (Chapter 7.5.)
    –    Infection with foot and mouth disease virus (Chapter 8.8.)
    –    Infection with Rift Valley fever virus (Chapter 8.16.)
    –    Infection with Trichinella spp. (Chapter 8.18.)
    –    Infection with Coxiella burnetii (Q fever) (a new Chapter 8.22.)
    –    Infection with Trypanosoma evansi (a new Chapter 8.23.)
    –    Rabbit haemorrhagic disease (Chapter 13.2.)
    –    Infection with African swine fever virus (Chapter 15.1.)
    –    Infection with Camelpox virus (a new Chapter 16.1)
    –    Terminology: Use of terms 'Competent Authority', 'Veterinary Authority' and 'Veterinary Services'.

    Details of the amendments made in this edition can be found in the 91st General Session **report** and Specialist
    Commissions **reports**, available on the World Organisation for Animal Health website (www.woah.org).

    I wish to thank the members of the Code Commission, Delegates, international experts and other Specialist
    Commissions for their expert advice. Thanks also to the World Organisation for Animal Health staff who contributed to
    the work that has resulted in the publication of this 32nd edition of the Terrestrial Code.

                                                       Dr Monique Eloit
                                                       Director General
                                              World Organisation for Animal Health

**Instance 3:**
*   **Chapter, Section, Page:** User's Guide, A. Introduction, 2), page ix
*   **Paragraph:**
    1)   The WOAH Terrestrial Animal Health Code (hereafter referred to as the Terrestrial Code) establishes standards
         for the improvement of terrestrial animal health and welfare and veterinary public health worldwide. The purpose
         of this guide is to advise the Veterinary Authorities of WOAH Member Countries on how to use the Terrestrial Code.
    2)   Veterinary Authorities should use the standards in the Terrestrial Code to set up measures providing for early
         detection, internal **reporting**, notification, control or eradication of pathogenic agents, including zoonotic ones, in
         terrestrial animals (mammals, birds, reptiles and bees) and preventing their spread via international trade in
         animals and animal products, while avoiding unjustified sanitary barriers to trade.
    3)   WOAH standards are based on the most recent scientific and technical information. Correctly applied, they protect
         animal health and welfare and veterinary public health during production and trade in animals and animal products,
         and in the use of animals.
    4)   The absence of chapters, articles or recommendations on particular pathogenic agents or commodities does not
         preclude the application of appropriate sanitary measures by the Veterinary Authorities, provided they are based
         on risk analyses conducted in accordance with the Terrestrial Code.
    5)   The year that a chapter was first adopted and the year of its last revision are noted at the end of each chapter.
    6)   The complete text of the Terrestrial Code is available on WOAH Web site and individual chapters may be
         downloaded from: https://www.woah.org/.

**Instance 4:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks **reported** from the time of the
         initial notification through to the final **report**. **Reports** of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, **reports** shall conform as closely as possible to the
         WOAH disease **reporting** format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be **reported**, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their **reports**, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 5:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks **reported** from the time of the
         initial notification through to the final **report**. **Reports** of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, **reports** shall conform as closely as possible to the
         WOAH disease **reporting** format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be **reported**, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their **reports**, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 6:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks **reported** from the time of the
         initial notification through to the final **report**. **Reports** of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, **reports** shall conform as closely as possible to the
         WOAH disease **reporting** format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be **reported**, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their **reports**, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 7:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks reported from the time of the
         initial notification through to the final report. **Reports** of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, **reports** shall conform as closely as possible to the
         WOAH disease **reporting** format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be **reported**, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their **reports**, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 8:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.2., page 1
*   **Paragraph:**
    1)   Member Countries shall make available to other Member Countries, through WOAH, whatever information is
         necessary to minimise the spread of important animal diseases, and their pathogenic agents, and to assist in
         achieving better worldwide control of these diseases.
    2)   To achieve this, Member Countries shall comply with the notification requirements specified in Articles 1.1.3. and
         1.1.4.
    3)   For the purposes of this chapter, an “event” means a single outbreak or a group of epidemiologically related
         outbreaks of a given listed disease or emerging disease that is the subject of a notification. An event is specific to
         a pathogenic agent and strain, when appropriate, and includes all related outbreaks reported from the time of the
         initial notification through to the final report. Reports of an event include susceptible species, the number and
         geographical distribution of affected animals and epidemiological units.
    4)   To assist in the clear and concise exchange of information, reports shall conform as closely as possible to the
         WOAH disease **reporting** format.
    5)   The detection of the pathogenic agent of a listed disease in an animal should be **reported**, even in the absence of
         clinical signs. Recognising that scientific knowledge concerning the relationship between diseases and their
         pathogenic agents is constantly developing and that the presence of a pathogenic agent does not necessarily imply
         the presence of a disease, Member Countries shall ensure, through their **reports**, that they comply with the spirit
         and intention of point 1 above.
    6)   In addition to notifying new findings in accordance with Articles 1.1.3. and 1.1.4., Member Countries shall also
         provide information on the measures taken to prevent the spread of diseases. Information shall include biosecurity
         and sanitary measures, including restrictions applied to the movement of animals, animal products, biological
         products and other miscellaneous objects which could by their nature be responsible for the transmission of
         diseases. In the case of diseases transmitted by vectors, the measures taken against such vectors shall also be
         specified.

**Instance 9:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly **reports** subsequent to a notification under point 1 above, to provide further information on the evolution of
         the event which justified the notification. These **reports** should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly **reporting** under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final **report** should be submitted;
    3)   six-monthly **reports** on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual **reports** concerning any other information of significance to other Member Countries.

**Instance 10:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly **reports** subsequent to a notification under point 1 above, to provide further information on the evolution of
         the event which justified the notification. These **reports** should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly **reporting** under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final **report** should be submitted;
    3)   six-monthly **reports** on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual **reports** concerning any other information of significance to other Member Countries.

**Instance 11:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly reports subsequent to a notification under point 1 above, to provide further information on the evolution of
         the event which justified the notification. These reports should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly **reporting** under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final **report** should be submitted;
    3)   six-monthly **reports** on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual **reports** concerning any other information of significance to other Member Countries.

**Instance 12:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly reports subsequent to a notification under point 1 above, to provide further information on the evolution of
         the event which justified the notification. These reports should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly reporting under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final **report** should be submitted;
    3)   six-monthly **reports** on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual **reports** concerning any other information of significance to other Member Countries.

**Instance 13:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.3., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.3.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   in accordance with relevant provisions in the disease-specific chapters, notification, through the World Animal
         Health Information System (WAHIS) or by fax or email within 24 hours, of any of the following events:

         a)   first occurrence of a listed disease in a country, a zone or a compartment;
         b)   recurrence of an eradicated listed disease in a country, a zone or a compartment following the final report that
              declared the event ended;
         c)   first occurrence of a new strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment;
         d)   recurrence of an eradicated strain of a pathogenic agent of a listed disease in a country, a zone or a
              compartment following the final report that declared the event ended;
         e)   a sudden and unexpected change in the distribution or increase in incidence or virulence of, or morbidity or
              mortality caused by, the pathogenic agent of a listed disease present within a country, a zone or a
              compartment;
         f)   occurrence of a listed disease in an unusual host species;
    2)   weekly reports subsequent to a notification under point 1 above, to provide further information on the evolution of
         the event which justified the notification. These reports should continue until the listed disease has been eradicated
         or the situation has become sufficiently stable that six-monthly reporting under point 3 will satisfy the obligation of
         the Member Country. For each event notified, a final report should be submitted;
    3)   six-monthly **reports** on the absence or presence and evolution of listed diseases and information of epidemiological
         significance to other Member Countries;
    4)   annual **reports** concerning any other information of significance to other Member Countries.

**Instance 14:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.4., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.4.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   a notification through WAHIS or by fax or email, when an emerging disease has been detected in a country, a zone
         or a compartment;

    2)   periodic **reports** subsequent to a notification of an emerging disease:
         a)   for the time necessary to have reasonable certainty that:
              i)    the infection or infestation has been eradicated; or
              ii)   the situation has become stable;
         OR
         b)   until sufficient scientific information is available to determine whether it meets the criteria for inclusion in the
              WOAH list as described in Chapter 1.2.;
    3)   a final **report** once point 2 a) or 2 b) above has been complied with.

**Instance 15:**
*   **Chapter, Section, Page:** Chapter 1.1. Notification of diseases and provision of epidemiological information, Article 1.1.4., page 2
*   **Paragraph:**
    CHAPTER 1.1.- Notification of diseases and provision of epidemiological information

                                                       Article 1.1.4.

    Veterinary Authorities shall, under the responsibility of the Delegate, send to the Headquarters:

    1)   a notification through WAHIS or by fax or email, when an emerging disease has been detected in a country, a zone
         or a compartment;

    2)   periodic **reports** subsequent to a notification of an emerging disease:
         a)   for the time necessary to have reasonable certainty that:
              i)    the infection or infestation has been eradicated; or
              ii)   the situation has become stable;
         OR
         b)   until sufficient scientific information is available to determine whether it meets the criteria for inclusion in the
              WOAH list as described in Chapter 1.2.;
    3)   a final **report** once point 2 a) or 2 b) above has been complied with.

**Instance 16:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 17:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 18:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 19:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 20:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 21:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 22:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.4., page 10
*   **Paragraph:**
    CHAPTER 1.4.- Animal health surveillance


                                                      Article 1.4.4.


    Surveillance methods

    Surveillance systems routinely use data collected by probability-based or non-probability-based methods, either alone
    or in combination. A wide variety of surveillance sources may be available. These vary in their primary purpose and the
    type of surveillance information they are able to provide.


    1.   Disease **reporting** systems

         Disease **reporting** systems are based on **reporting** of animal health-related events to the Veterinary Authority. Data
         derived from disease **reporting** systems can be used in combination with other data sources to substantiate claims
         of animal health status, to generate data for risk analysis or for early warning and response. Effective laboratory
         support is an important component of any **reporting** system. **Reporting** systems relying on laboratory confirmation
         of suspected clinical cases should use tests that have high specificity as described in the Terrestrial Manual.


         Whenever the responsibility for disease **reporting** falls outside the scope of the Veterinary Authority, for example
         human cases of zoonotic diseases or infections or infestations in wildlife, effective communication and data sharing
         should be established between the Veterinary Authority and other relevant authorities.

         Participatory surveillance methods may be useful to collect epidemiological data that can support disease **reporting**
         systems.

**Instance 23:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.3., page 9
*   **Paragraph:**
    2.   Implementation of the surveillance system
         a)   Diagnostic tests
              The sensitivity and specificity values of the tests used should be specified for target species and the method
              used to estimate these values should be documented in accordance with the Terrestrial Manual.
              Samples from a number of animals or units may be pooled and subjected to a testing protocol. The results
              should be interpreted using sensitivity and specificity values that have been determined or estimated for that
              particular pool size and testing procedure.
         b)   Data collection and management
              The success of a surveillance system is dependent on a reliable process for data collection and management.
              The process may be based on paper or electronic records. Even where data are collected for non-survey
              purposes (e.g. during disease control interventions, inspections for movement control or during disease
              eradication schemes), the consistency and quality of data collection and event **reporting** in a format that
              facilitates analysis is critical. Software may offer the possibility of extraction of multiple source data for
              aggregation and analysis. Factors influencing the quality of collected data include:
              –    the distribution of, and communication between, those involved in generating and transferring data from
                   the field to a centralised location; this requires effective collaboration among all stakeholders, such as
                   government or non-governmental organisations, and others, particularly for data involving wildlife;
              –    the ability of the data processing system to detect missing, inconsistent or inaccurate data, and to
                   address these problems;
              –    maintenance of raw data rather than the compilation of summary data;
              –    minimisation of transcription errors during data processing and communication.

**Instance 24:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.5., page 13
*   **Paragraph:**
    Early warning systems

    An early warning system is essential for the timely detection, **reporting** and communication of occurrence, incursion or
    emergence of diseases, infections or infestations and is an integral component of emergency preparedness. It should
    be under the control of the Veterinary Authority and should include the following:
    1)   appropriate access to, and authority over, the target animal populations by the Veterinary Services;
    2)   access to laboratories capable of diagnosing and differentiating relevant infections or infestations;
    3)   training and awareness programmes for veterinarians, veterinary paraprofessionals, animal owners or keepers and
         others involved in handling animals at the farm or other places where they are kept during their transport or at the
         slaughterhouse/abattoir, for detecting and **reporting** unusual animal health incidents;
    4)   a legal obligation by veterinarians and other relevant stakeholders to **report** suspected cases or cases of notifiable
         diseases or emerging diseases to the Veterinary Authority, including the description of the findings;
    5)   epidemiological investigations of suspected cases and cases conducted by the Veterinary Services in order to
         confirm cases and to acquire accurate knowledge of the situation for further action.
         All suspected case investigations should provide a result, either positive or negative. Criteria should be established
         in advance for a case definition. Confirmation can be made on clinical and post-mortem grounds, epidemiological
         information, laboratory test results or a combination of these, in accordance with relevant articles of the Terrestrial
         Code or Terrestrial Manual;
    6)   effective systems of communication between the Veterinary Authority and relevant stakeholders;
    7)   a national chain of command.

**Instance 25:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.5., page 13
*   **Paragraph:**
    Early warning systems

    An early warning system is essential for the timely detection, **reporting** and communication of occurrence, incursion or
    emergence of diseases, infections or infestations and is an integral component of emergency preparedness. It should
    be under the control of the Veterinary Authority and should include the following:
    1)   appropriate access to, and authority over, the target animal populations by the Veterinary Services;
    2)   access to laboratories capable of diagnosing and differentiating relevant infections or infestations;
    3)   training and awareness programmes for veterinarians, veterinary paraprofessionals, animal owners or keepers and
         others involved in handling animals at the farm or other places where they are kept during their transport or at the
         slaughterhouse/abattoir, for detecting and **reporting** unusual animal health incidents;
    4)   a legal obligation by veterinarians and other relevant stakeholders to **report** suspected cases or cases of notifiable
         diseases or emerging diseases to the Veterinary Authority, including the description of the findings;
    5)   epidemiological investigations of suspected cases and cases conducted by the Veterinary Services in order to
         confirm cases and to acquire accurate knowledge of the situation for further action.
         All suspected case investigations should provide a result, either positive or negative. Criteria should be established
         in advance for a case definition. Confirmation can be made on clinical and post-mortem grounds, epidemiological
         information, laboratory test results or a combination of these, in accordance with relevant articles of the Terrestrial
         Code or Terrestrial Manual;
    6)   effective systems of communication between the Veterinary Authority and relevant stakeholders;
    7)   a national chain of command.

**Instance 26:**
*   **Chapter, Section, Page:** Chapter 1.4. Animal health surveillance, Article 1.4.5., page 13
*   **Paragraph:**
    Early warning systems

    An early warning system is essential for the timely detection, **reporting** and communication of occurrence, incursion or
    emergence of diseases, infections or infestations and is an integral component of emergency preparedness. It should
    be under the control of the Veterinary Authority and should include the following:
    1)   appropriate access to, and authority over, the target animal populations by the Veterinary Services;
    2)   access to laboratories capable of diagnosing and differentiating relevant infections or infestations;
    3)   training and awareness programmes for veterinarians, veterinary paraprofessionals, animal owners or keepers and
         others involved in handling animals at the farm or other places where they are kept during their transport or at the
         slaughterhouse/abattoir, for detecting and reporting unusual animal health incidents;
    4)   a legal obligation by veterinarians and other relevant stakeholders to **report** suspected cases or cases of notifiable
         diseases or emerging diseases to the Veterinary Authority, including the description of the findings;
    5)   epidemiological investigations of suspected cases and cases conducted by the Veterinary Services in order to
         confirm cases and to acquire accurate knowledge of the situation for further action.
         All suspected case investigations should provide a result, either positive or negative. Criteria should be established
         in advance for a case definition. Confirmation can be made on clinical and post-mortem grounds, epidemiological
         information, laboratory test results or a combination of these, in accordance with relevant articles of the Terrestrial
         Code or Terrestrial Manual;
    6)   effective systems of communication between the Veterinary Authority and relevant stakeholders;
    7)   a national chain of command.

**Instance 27:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.1., page 23
*   **Paragraph:**
    3.   AHS eradication
         a)   History. If infection has never occurred in the country, or has not occurred within the past 25 years, state
              explicitly whether or not the country is applying for recognition of historical freedom according to
              Article 1.4.6. of the Terrestrial Code.
              If infection has occurred in the country within the past 25 years, provide a description of the AHS history in
              the country, with emphasis on recent years. If applicable, provide tables and maps showing the date of first
              detection, the sources and routes of introduction of infection, the temporal and spatial distribution (number
              and location of outbreaks per year), the susceptible species involved, and the date of last case or eradication
              in the country.
         b)   Strategy. Describe how AHS was controlled and eradicated (e.g. isolation of cases, stamping-out policy,
              zoning, movement control, protection of equids against vectors). Provide the time frame for eradication.
              Describe and justify the corrective actions that have been implemented to prevent future outbreaks of AHS in
              response to any past incursions of AHS virus.
         c)   Vaccines and vaccination. Briefly answer the following:
              i)     Is there any legislation that prohibits vaccination? If so:
                     –    Provide the date when vaccination was formally prohibited;
                     –    Provide information on cases of detection of illegal vaccination during the **reporting** period and
                          actions taken in response to the detection.
              ii)    Was vaccination ever used in the country? If so:
                     –    Provide the date when the last vaccination was carried out;
                     –    What type of vaccine was used?
                     –    What species were vaccinated?
                     –    How were vaccinated animals identified?
                     –    What was the fate of those animals?
              iii)   In addition, if vaccination was applied during the past 24 months, provide a description and justification
                     of the vaccination strategy and programme, including the following:
                     –    the vaccine strains;
                     –    the species vaccinated;
                     –    identification of vaccinated animals;
                     –    the way in which the vaccination of animals was certified or **reported** and the records maintained;
                     –    evidence that the vaccine used complies with Chapter 3.5.1. of the Terrestrial Manual.
         d)   Provide a description of the legislation, organisation and implementation of the eradication campaign. Outline
              the legislation applicable to the eradication and how the campaign was organised at different levels. Indicate
              if detailed operational guidelines exist and give a brief summary.

**Instance 28:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.1., page 23
*   **Paragraph:**
    3.   AHS eradication
         a)   History. If infection has never occurred in the country, or has not occurred within the past 25 years, state
              explicitly whether or not the country is applying for recognition of historical freedom according to
              Article 1.4.6. of the Terrestrial Code.
              If infection has occurred in the country within the past 25 years, provide a description of the AHS history in
              the country, with emphasis on recent years. If applicable, provide tables and maps showing the date of first
              detection, the sources and routes of introduction of infection, the temporal and spatial distribution (number
              and location of outbreaks per year), the susceptible species involved, and the date of last case or eradication
              in the country.
         b)   Strategy. Describe how AHS was controlled and eradicated (e.g. isolation of cases, stamping-out policy,
              zoning, movement control, protection of equids against vectors). Provide the time frame for eradication.
              Describe and justify the corrective actions that have been implemented to prevent future outbreaks of AHS in
              response to any past incursions of AHS virus.
         c)   Vaccines and vaccination. Briefly answer the following:
              i)     Is there any legislation that prohibits vaccination? If so:
                     –    Provide the date when vaccination was formally prohibited;
                     –    Provide information on cases of detection of illegal vaccination during the reporting period and
                          actions taken in response to the detection.
              ii)    Was vaccination ever used in the country? If so:
                     –    Provide the date when the last vaccination was carried out;
                     –    What type of vaccine was used?
                     –    What species were vaccinated?
                     –    How were vaccinated animals identified?
                     –    What was the fate of those animals?
              iii)   In addition, if vaccination was applied during the past 24 months, provide a description and justification
                     of the vaccination strategy and programme, including the following:
                     –    the vaccine strains;
                     –    the species vaccinated;
                     –    identification of vaccinated animals;
                     –    the way in which the vaccination of animals was certified or **reported** and the records maintained;
                     –    evidence that the vaccine used complies with Chapter 3.5.1. of the Terrestrial Manual.
         d)   Provide a description of the legislation, organisation and implementation of the eradication campaign. Outline
              the legislation applicable to the eradication and how the campaign was organised at different levels. Indicate
              if detailed operational guidelines exist and give a brief summary.

**Instance 29:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.1., page 23
*   **Paragraph:**
    4.   AHS diagnosis
         Provide documentary evidence that the relevant provisions of Chapters 1.1.2., 1.1.3. and 3.5.1. of the Terrestrial
         Manual are applied. The following points should be addressed:
         a)   Is AHS laboratory diagnosis carried out in the country? If so, provide an overview of the AHS-approved
              laboratories in the country, including the following:
              i)     How the work is shared between different laboratories, logistics for shipment of samples, the follow-up
                     procedures and the time frame for **reporting** results;
              ii)    Details of test capability and the types of tests undertaken and their performance for their applied use
                     (specificity and sensitivity per type of test). Provide details of the number of AHS tests performed in the
                     past 24 months in national laboratories and in laboratories in other countries, if relevant;
              iii)   Procedures for quality assurance and for the official accreditation of laboratories. Give details of formal
                     internal quality management systems, e.g. Good Laboratory Practice, ISO, etc. that exist in, or are
                     planned for, the laboratory system;
              iv)    Provide details of performance in inter-laboratory validation tests (ring trials), including the most recent
                     results and, if applicable, the corrective measures applied;
              v)     Provide details of the handling of live pathogenic agent, including a description of the biosecurity and
                     biosafety measures applied;
              vi)    Provide a table identifying the tests carried out by each of the laboratories where they are performed,
                     the quality accreditation and biosecurity standards followed and the proficiency tests carried out.
         b)   If AHS laboratory diagnosis is not carried out in the country, provide the names of the laboratories in other
              countries providing the service as well as the arrangements in place, including logistics for shipment of
              samples and the time frame for **reporting** results.

**Instance 30:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.1., page 24
*   **Paragraph:**
    5.   AHS surveillance
         Provide documentary evidence that surveillance for AHS in the country complies with Articles 12.1.11. to
         12.1.13. of the Terrestrial Code, and Chapter 3.5.1. of the Terrestrial Manual. The following information should be
         included:
         a)   What are the criteria for raising a suspicion of AHS? What is the procedure to notify (by whom and to whom)
              and what incentives are there for **reporting** and what penalties are involved for failure to **report**?
         b)   Describe how clinical surveillance is conducted, including which equine sectors are included in clinical
              surveillance, such as establishments, markets, fairs, slaughterhouses/abattoirs, check points, etc.
              Provide a summary table indicating, for the past 24 months, the number of suspected cases, the number of
              samples tested for AHS, species, type of sample, testing methods and results (including differential
              diagnosis). Provide an indication of the timelines of the response including completion of testing to confirm or
              exclude AHS. Provide details of follow-up actions taken on all suspicious and positive results.
         c)   Other surveillance. Is surveillance undertaken as described in Article 12.1.13., specifically:
              i)     Serological surveillance.
              ii)    Virological surveillance including genome or antigen detection.
              iii)   Sentinel animals.
              iv)    Vector surveillance.
              If so, provide detailed information on the target population, design prevalence, confidence level, sample size,
              stratification, sampling methods and diagnostic tests used in accordance with Articles 12.1.11. and
              12.1.13. of the Terrestrial Code. How frequently are they conducted? Which equine species are included? Are
              wildlife species included? If not, explain the rationale.
              Provide a summary table and maps indicating detailed results for at least the past 24 months. Provide details
              of follow-up actions taken on all suspicious and positive results and how these findings are acted upon.
              Provide criteria for selection of populations for targeted surveillance and numbers of equids examined and
              samples tested in diagnostic laboratories. Provide details of the methods selected and applied for monitoring
              the performance of the surveillance programme including indicators.
         d)   Provide information on risks in the different equine sectors, and provide evidence that targeted studies are
              implemented to address gaps (e.g. targeted serological surveys, active surveillance, participatory
              epidemiology studies, risk assessments, etc.). Provide evidence of how the knowledge acquired through
              these activities assisted in more effective implementation of control measures.
         e)   Provide details of the oversight of surveillance programmes by the Veterinary Services including training
              programmes for personnel involved in clinical, serological, virological and other surveillance, and the
              approaches used to increase community involvement in AHS surveillance programmes.

**Instance 31:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.1., page 24
*   **Paragraph:**
    5.   AHS surveillance
         Provide documentary evidence that surveillance for AHS in the country complies with Articles 12.1.11. to
         12.1.13. of the Terrestrial Code, and Chapter 3.5.1. of the Terrestrial Manual. The following information should be
         included:
         a)   What are the criteria for raising a suspicion of AHS? What is the procedure to notify (by whom and to whom)
              and what incentives are there for **reporting** and what penalties are involved for failure to **report**?
         b)   Describe how clinical surveillance is conducted, including which equine sectors are included in clinical
              surveillance, such as establishments, markets, fairs, slaughterhouses/abattoirs, check points, etc.
              Provide a summary table indicating, for the past 24 months, the number of suspected cases, the number of
              samples tested for AHS, species, type of sample, testing methods and results (including differential
              diagnosis). Provide an indication of the timelines of the response including completion of testing to confirm or
              exclude AHS. Provide details of follow-up actions taken on all suspicious and positive results.
         c)   Other surveillance. Is surveillance undertaken as described in Article 12.1.13., specifically:
              i)     Serological surveillance.
              ii)    Virological surveillance including genome or antigen detection.
              iii)   Sentinel animals.
              iv)    Vector surveillance.
              If so, provide detailed information on the target population, design prevalence, confidence level, sample size,
              stratification, sampling methods and diagnostic tests used in accordance with Articles 12.1.11. and
              12.1.13. of the Terrestrial Code. How frequently are they conducted? Which equine species are included? Are
              wildlife species included? If not, explain the rationale.
              Provide a summary table and maps indicating detailed results for at least the past 24 months. Provide details
              of follow-up actions taken on all suspicious and positive results and how these findings are acted upon.
              Provide criteria for selection of populations for targeted surveillance and numbers of equids examined and
              samples tested in diagnostic laboratories. Provide details of the methods selected and applied for monitoring
              the performance of the surveillance programme including indicators.
         d)   Provide information on risks in the different equine sectors, and provide evidence that targeted studies are
              implemented to address gaps (e.g. targeted serological surveys, active surveillance, participatory
              epidemiology studies, risk assessments, etc.). Provide evidence of how the knowledge acquired through
              these activities assisted in more effective implementation of control measures.
         e)   Provide details of the oversight of surveillance programmes by the Veterinary Services including training
              programmes for personnel involved in clinical, serological, virological and other surveillance, and the
              approaches used to increase community involvement in AHS surveillance programmes.

**Instance 32:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.2., page 27
*   **Paragraph:**
    3.   AHS eradication
         a)   History. If infection has never occurred in the country, or has not occurred within the past 25 years, state
              explicitly whether or not the zone is applying for recognition of historical freedom according to Article 1.4.6. of
              the Terrestrial Code.
              If infection has occurred in the zone within the past 25 years, provide a description of the AHS history in the
              country and zone, with emphasis on recent years. If applicable, provide tables and maps showing the date of
              first detection, the sources and routes of introduction of infection, the temporal and spatial distribution
              (number and location of outbreaks per year), the susceptible species involved, and the date of last case or
              eradication in the zone.
         b)   Strategy. Describe how AHS was controlled and eradicated in the zone (e.g. isolation of cases, stamping-out
              policy, zoning, movement control, protection of equids against vectors). Provide the time frame for
              eradication. Describe and justify the corrective actions that have been implemented to prevent future
              outbreaks of AHS in response to any past incursions of AHS virus.
         c)   Vaccines and vaccination. Briefly answer the following:
              i)    Is there any legislation that prohibits vaccination? If so:
                    –    Provide the date when vaccination was formally prohibited;
                    –    Provide information on cases of detection of illegal vaccination during the **reporting** period and
                         actions taken in response to the detection.
              ii)   Was vaccination ever used in the country? If so:
                    –    Provide the date when the last vaccination was carried out;
                    –    What type of vaccine was used in the zone and the rest of the country?
                    –    What species were vaccinated?
                    –    How were vaccinated animals identified?
                    –    What was the fate of those animals?
              iii)   In addition, if vaccination was applied during the past 24 months, provide a description and justification
                     of the vaccination strategy and programme, including the following:

                     –    the vaccine strains;
                     –    the species vaccinated;
                     –    identification of vaccinated animals;
                     –    the way in which the vaccination of animals was certified or **reported** and the records maintained;
                     –    evidence that the vaccine used complies with Chapter 3.5.1. of the Terrestrial Manual.
         d)   Provide a description of the legislation, organisation and implementation of the eradication campaign. Outline
              the legislation applicable to the eradication and how the campaign was organised at different levels. Indicate
              if detailed operational guidelines exist and give a brief summary.

**Instance 33:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.2., page 27
*   **Paragraph:**
    3.   AHS eradication
         a)   History. If infection has never occurred in the country, or has not occurred within the past 25 years, state
              explicitly whether or not the zone is applying for recognition of historical freedom according to Article 1.4.6. of
              the Terrestrial Code.
              If infection has occurred in the zone within the past 25 years, provide a description of the AHS history in the
              country and zone, with emphasis on recent years. If applicable, provide tables and maps showing the date of
              first detection, the sources and routes of introduction of infection, the temporal and spatial distribution
              (number and location of outbreaks per year), the susceptible species involved, and the date of last case or
              eradication in the zone.
         b)   Strategy. Describe how AHS was controlled and eradicated in the zone (e.g. isolation of cases, stamping-out
              policy, zoning, movement control, protection of equids against vectors). Provide the time frame for
              eradication. Describe and justify the corrective actions that have been implemented to prevent future
              outbreaks of AHS in response to any past incursions of AHS virus.
         c)   Vaccines and vaccination. Briefly answer the following:
              i)    Is there any legislation that prohibits vaccination? If so:
                    –    Provide the date when vaccination was formally prohibited;
                    –    Provide information on cases of detection of illegal vaccination during the **reporting** period and
                         actions taken in response to the detection.
              ii)   Was vaccination ever used in the country? If so:
                    –    Provide the date when the last vaccination was carried out;
                    –    What type of vaccine was used in the zone and the rest of the country?
                    –    What species were vaccinated?
                    –    How were vaccinated animals identified?
                    –    What was the fate of those animals?
              iii)   In addition, if vaccination was applied during the past 24 months, provide a description and justification
                     of the vaccination strategy and programme, including the following:

                     –    the vaccine strains;
                     –    the species vaccinated;
                     –    identification of vaccinated animals;
                     –    the way in which the vaccination of animals was certified or **reported** and the records maintained;
                     –    evidence that the vaccine used complies with Chapter 3.5.1. of the Terrestrial Manual.
         d)   Provide a description of the legislation, organisation and implementation of the eradication campaign. Outline
              the legislation applicable to the eradication and how the campaign was organised at different levels. Indicate
              if detailed operational guidelines exist and give a brief summary.

**Instance 34:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.2., page 28
*   **Paragraph:**
    4.   AHS diagnosis

         Provide documentary evidence that the relevant provisions of Chapters 1.1.2., 1.1.3. and 3.5.1. of the Terrestrial
         Manual are applied. The following points should be addressed:

         a)   Is AHS laboratory diagnosis carried out in the country? If so, provide an overview of the AHS-approved
              laboratories in the country. Indicate the laboratories where samples originating from the zone are diagnosed.
              Address the following points:

              i)     How the work is shared between different laboratories, logistics for shipment of samples, the follow-up
                     procedures and the time frame for **reporting** results;

              ii)    Details of test capability and the types of tests undertaken and their performance for their applied use
                     (specificity and sensitivity per type of test). Provide details of the number of AHS tests performed in the
                     past 24 months in national laboratories and in laboratories in other countries, if relevant;

              iii)   Procedures for quality assurance and for the official accreditation of laboratories. Give details of formal
                     internal quality management systems, e.g. Good Laboratory Practice, ISO, etc. that exist in, or are
                     planned for, the laboratory system;
              iv)    Provide details of performance in inter-laboratory validation tests (ring tests), including the most recent
                     results and, if applicable, the corrective measures applied;
              v)     Provide details of the handling of live pathogenic agent, including a description of the biosecurity and
                     biosafety measures applied;
              vi)    Provide a table identifying the tests carried out by each of the laboratories where they are performed,
                     the quality accreditation and biosecurity standards followed and the proficiency tests carried out.
         b)   If AHS laboratory diagnosis is not carried out in the country, provide the names of the laboratories in other
              countries providing the service as well as the arrangements in place, including logistics for shipment of
              samples and the time frame for **reporting** results.

**Instance 35:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.2., page 28
*   **Paragraph:**
    5.   AHS surveillance

         Provide documentary evidence that surveillance for AHS in the zone complies with Articles 12.1.11. to 12.1.13. of
         the Terrestrial Code, and Chapter 3.5.1. of the Terrestrial Manual. The following information should be included:
         a)   What are the criteria for raising a suspicion of AHS? What is the procedure to notify (by whom and to whom)
              and what incentives are there for **reporting** and what penalties are involved for failure to **report**?
         b)   Describe how clinical surveillance is conducted, including which equine sectors are included in clinical
              surveillance, such as establishments, markets, fairs, slaughterhouses/abattoirs, check points, etc.

              Provide a summary table indicating, for the past 24 months, the number of suspected cases, the number of
              samples tested for AHS, species, type of sample, testing methods and results (including differential
              diagnosis). Provide an indication of the timelines of the response including completion of testing to confirm or
              exclude AHS. Provide details of follow-up actions taken on all suspicious and positive results.
         c)   Other surveillance. Is surveillance undertaken as described in Article 12.1.13., specifically:
              i)     Serological surveillance.
              ii)    Virological surveillance including genome or antigen detection.

**Instance 36:**
*   **Chapter, Section, Page:** Chapter 1.7. Application for official recognition by WOAH of free status for African horse sickness, Article 1.7.2., page 28
*   **Paragraph:**
    5.   AHS surveillance

         Provide documentary evidence that surveillance for AHS in the zone complies with Articles 12.1.11. to 12.1.13. of
         the Terrestrial Code, and Chapter 3.5.1. of the Terrestrial Manual. The following information should be included:
         a)   What are the criteria for raising a suspicion of AHS? What is the procedure to notify (by whom and to whom)
              and what incentives are there for **reporting** and what penalties are involved for failure to **report**?
         b)   Describe how clinical surveillance is conducted, including which equine sectors are included in clinical
              surveillance, such as establishments, markets, fairs, slaughterhouses/abattoirs, check points, etc.

              Provide a summary table indicating, for the past 24 months, the number of suspected cases, the number of
              samples tested for AHS, species, type of sample, testing methods and results (including differential
              diagnosis). Provide an indication of the timelines of the response including completion of testing to confirm or
              exclude AHS. Provide details of follow-up actions taken on all suspicious and positive results.
         c)   Other surveillance. Is surveillance undertaken as described in Article 12.1.13., specifically:
              i)     Serological surveillance.
              ii)    Virological surveillance including genome or antigen detection.

**Instance 37:**
*   **Chapter, Section, Page:** Chapter 1.8. Application for official recognition by WOAH of risk status for bovine spongiform encephalopathy, Article 1.8.5., page 38
*   **Paragraph:**
    Article 1.8.5.

    Surveillance (point 2 of Article 11.4.4.)

    Article 11.4.20. describes the criteria that underpin a credible surveillance programme, together with an overview of the
    range and progression of clinical signs that bovines affected by BSE are likely to exhibit.

    Requirements under point 2 of Article 11.4.20. are focused on subsets of the bovine population where BSE is more
    likely to be detected.

    The Member applying for recognition of a negligible or a controlled BSE risk status should submit documentary
    evidence that the provisions of point 3 of Article 11.4.20. have been effectively implemented.

    For the purposes of surveillance, the period of interest is the preceding eight years (Articles 11.4.4. and 11.4.5.).

    1.   Awareness and training programmes (point 3 a) of Article 11.4.20.)
         Ongoing awareness and training programmes are essential to ensure that all stakeholders are familiar with clinical
         signs suggestive of BSE (those described in point 1 of Article 11.4.20.) as well as their statutory **reporting**
         requirements.
         a)    Describe the stakeholder groups targeted for BSE awareness and training programmes. Describe the
               methods used to identify stakeholder groups within the jurisdiction and methods used to identify how, for
               example, the size and characteristics of the stakeholder group changes over time.
         b)    Describe the type(s) of awareness and training programmes implemented for specific stakeholder groups.
               Describe how these programmes are adapted to meet the specific obligations and activities of each
               stakeholder group involved in caring for livestock, as well as the protocols for sample collection and
               submission by veterinarians and animal health technicians.
         c)    Provide information on the number of awareness and training activities, the stakeholder groups targeted, the
               number of individuals reached per activity (if available), and the geographical coverage of these activities.
         d)    Provide a description including examples of materials used in the awareness programme such as training
               manuals, supporting documents such as publications in local newspapers and farming magazines, pamphlets
               and videos (weblinks to supporting documents in one of the WOAH official languages may also be provided,
               where they exist).
         e)    Provide details on how the effectiveness of the awareness and training programmes is evaluated.
         f)    Provide details of any contingency or preparedness plan for BSE.

    2.   BSE **reporting** system (point 3 b) of Article 11.4.20.)
         a)    Describe the BSE **reporting** system, including the date of implementation of any supporting legislation and
               associated policies making BSE a notifiable disease. Indicate if a definition for a suspicion of BSE' exists. If
               appropriate, outline relevant legislation in the table under Article 1.8.2.
         b)    Describe the supportive measures in place for targeting animals that show signs of the clinical spectrum of
               BSE and for **reporting** of animals described in points 2 a) to 2 d) of Article 11.4.20., such as incentives,
               compensations or penalties.

**Instance 38:**
*   **Chapter, Section, Page:** Chapter 1.8. Application for official recognition by WOAH of risk status for bovine spongiform encephalopathy, Article 1.8.5., page 38
*   **Paragraph:**
    Article 1.8.5.

    Surveillance (point 2 of Article 11.4.4.)

    Article 11.4.20. describes the criteria that underpin a credible surveillance programme, together with an overview of the
    range and progression of clinical signs that bovines affected by BSE are likely to exhibit.

    Requirements under point 2 of Article 11.4.20. are focused on subsets of the bovine population where BSE is more
    likely to be detected.

    The Member applying for recognition of a negligible or a controlled BSE risk status should submit documentary
    evidence that the provisions of point 3 of Article 11.4.20. have been effectively implemented.

    For the purposes of surveillance, the period of interest is the preceding eight years (Articles 11.4.4. and 11.4.5.).

    1.   Awareness and training programmes (point 3 a) of Article 11.4.20.)
         Ongoing awareness and training programmes are essential to ensure that all stakeholders are familiar with clinical
         signs suggestive of BSE (those described in point 1 of Article 11.4.20.) as well as their statutory **reporting**
         requirements.
         a)    Describe the stakeholder groups targeted for BSE awareness and training programmes. Describe the
               methods used to identify stakeholder groups within the jurisdiction and methods used to identify how, for
               example, the size and characteristics of the stakeholder group changes over time.
         b)    Describe the type(s) of awareness and training programmes implemented for specific stakeholder groups.
               Describe how these programmes are adapted to meet the specific obligations and activities of each
               stakeholder group involved in caring for livestock, as well as the protocols for sample collection and
               submission by veterinarians and animal health technicians.
         c)    Provide information on the number of awareness and training activities, the stakeholder groups targeted, the
               number of individuals reached per activity (if available), and the geographical coverage of these activities.
         d)    Provide a description including examples of materials used in the awareness programme such as training
               manuals, supporting documents such as publications in local newspapers and farming magazines, pamphlets
               and videos (weblinks to supporting documents in one of the WOAH official languages may also be provided,
               where they exist).
         e)    Provide details on how the effectiveness of the awareness and training programmes is evaluated.
         f)    Provide details of any contingency or preparedness plan for BSE.

    2.   BSE **reporting** system (point 3 b) of Article 11.4.20.)
         a)    Describe the BSE **reporting** system, including the date of implementation of any supporting legislation and
               associated policies making BSE a notifiable disease. Indicate if a definition for a suspicion of BSE' exists. If
               appropriate, outline relevant legislation in the table under Article 1.8.2.
         b)    Describe the supportive measures in place for targeting animals that show signs of the clinical spectrum of
               BSE and for **reporting** of animals described in points 2 a) to 2 d) of Article 11.4.20., such as incentives,
               compensations or penalties.

**Instance 39:**
*   **Chapter, Section, Page:** Chapter 1.8. Application for official recognition by WOAH of risk status for bovine spongiform encephalopathy, Article 1.8.5., page 38
*   **Paragraph:**
    Article 1.8.5.

    Surveillance (point 2 of Article 11.4.4.)

    Article 11.4.20. describes the criteria that underpin a credible surveillance programme, together with an overview of the
    range and progression of clinical signs that bovines affected by BSE are likely to exhibit.

    Requirements under point 2 of Article 11.4.20. are focused on subsets of the bovine population where BSE is more
    likely to be detected.

    The Member applying for recognition of a negligible or a controlled BSE risk status should submit documentary
    evidence that the provisions of point 3 of Article 11.4.20. have been effectively implemented.

    For the purposes of surveillance, the period of interest is the preceding eight years (Articles 11.4.4. and 11.4.5.).

    1.   Awareness and training programmes (point 3 a) of Article 11.4.20.)
         Ongoing awareness and training programmes are essential to ensure that all stakeholders are familiar with clinical
         signs suggestive of BSE (those described in point 1 of Article 11.4.20.) as well as their statutory **reporting**
         requirements.
         a)    Describe the stakeholder groups targeted for BSE awareness and training programmes. Describe the
               methods used to identify stakeholder groups within the jurisdiction and methods used to identify how, for
               example, the size and characteristics of the stakeholder group changes over time.
         b)    Describe the type(s) of awareness and training programmes implemented for specific stakeholder groups.
               Describe how these programmes are adapted to meet the specific obligations and activities of each
               stakeholder group involved in caring for livestock, as well as the protocols for sample collection and
               submission by veterinarians and animal health technicians.
         c)    Provide information on the number of awareness and training activities, the stakeholder groups targeted, the
               number of individuals reached per activity (if available), and the geographical coverage of these activities.
         d)    Provide a description including examples of materials used in the awareness programme such as training
               manuals, supporting documents such as publications in local newspapers and farming magazines, pamphlets
               and videos (weblinks to supporting documents in one of the WOAH official languages may also be provided,
               where they exist).
         e)    Provide details on how the effectiveness of the awareness and training programmes is evaluated.
         f)    Provide details of any contingency or preparedness plan for BSE.

    2.   BSE **reporting** system (point 3 b) of Article 11.4.20.)
         a)    Describe the BSE **reporting** system, including the date of implementation of any supporting legislation and
               associated policies making BSE a notifiable disease. Indicate if a definition for a suspicion of BSE' exists. If
               appropriate, outline relevant legislation in the table under Article 1.8.2.
         b)    Describe the supportive measures in place for targeting animals that show signs of the clinical spectrum of
               BSE and for **reporting** of animals described in points 2 a) to 2 d) of Article 11.4.20., such as incentives,
               compensations or penalties.

## Findings for 'reportable disease'

No instances of 'reportable disease' or its synonyms were found in the provided document text.

